org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
java_version=21
neoforge_version=21.1.236
neoforge_loader_version_range=[1,)
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

# Project identity.
mod_id=create_bigger_crafters
mod_name=Create Bigger Crafters
mod_version=0.1.0
mod_group_id=com.radaeli.createbiggercrafters
mod_license=MIT
mod_authors=Radaeli
mod_description=Adds larger Factory Gauges for automating Create Mechanical Crafting recipes with packages.
